In [4]:
import pandas as pd

In [8]:
df = pd.read_csv("titanic.csv")

In [9]:
df.head()

   Name  Age  Marks
0   Ram   20     85
1  Sita   21     90
2  Hari   22     88

In [10]:
df.shape

(3, 3)

In [11]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Marks   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [13]:
df.describe()

        Age      Marks
count   3.0   3.000000
mean   21.0  87.666667
std     1.0   2.516611
min    20.0  85.000000
25%    20.5  86.500000
50%    21.0  88.000000
75%    21.5  89.000000
max    22.0  90.000000

In [14]:
df.isnull().sum()

Name     0
Age      0
Marks    0
dtype: int64

In [15]:
import os

print(os.getcwd())

C:\Users\24eu01105\Desktop\24eu01105